#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================
name: bcm 

on:
#  schedule:
#    - cron: 0 20 * * *
   push:
     branches: 
       - master
env:
   SSH_ACTIONS: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          
    - name: Clone source code
      env: 
        REPO_URL: https://github.com/Lienol/openwrt
        REPO_BRANCH: dev-19.07
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
      
    - name: Clone Config
      env: 
        REPO_URL: https://github.com/txdywy/openwrt-actions
      run: git clone --depth 1 $REPO_URL openwrt-config
      
    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a
    
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'ssh')
    - name: Make Defconfig
      run: |
          cd openwrt
          make defconfig

    - name: Make download
      run: |
          cd openwrt
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

    - name: Multi-thread compile
      run: |
          cd openwrt
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s

    - name: Single-thread compile
      if: failure()
      run: |
          cd openwrt
          make -j1 V=s
          

    - name: Assemble artifact
      run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find openwrt/bin/targets/brcm2708/bcm2710/ -name "*" | xargs -i mv -f {} ./artifact/
          find openwrt/bin/targets/brcm2708/bcm2710/ -name "*combined*img*" | xargs -i mv -f {} ./artifact/
          find openwrt/bin/packages/aarch64_cortex-a53/lienol/ -name "*ipk*" | xargs -i mv -f {} ./artifact/
          cp /home/runner/work/openwrt-actions/openwrt-actions/openwrt/bin/targets/brcm2708/bcm2710/openwrt-brcm2708-bcm2710-rpi-3-ext4-sysupgrade.img.gz ./artifact/.
          cp -R /home/runner/work/openwrt-actions/openwrt-actions/openwrt/* ./artifact/.

       
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt firmware
        path: openwrt/bin
